name: meetups
description: Dev meetups is a flutter project to a course of the Alura
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  firebase_messaging:
  device_info_plus:
  shared_preferences:
  firebase_core:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true